name: appmanagement
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^2.0.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  flutter_screenutil: ^5.6.0
  firebase_core: ^2.2.0
  google_sign_in: ^5.4.2
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/logos/
    # - assets/profiles/
    # - assets/icons/
  fonts: 
    - family: proxima
      fonts: 
        - asset: assets/fonts/Proxima Nova/Proxima Nova Alt Bold.otf
        - asset: assets/fonts/Proxima Nova/ProximaNova-Regular.otf

